file_format: "1"
id: hillside46
name: Hillside View
type: shield
url: https://github.com/wannabecoffeenerd/hillside
requires:
  - pro_micro
exposes:
  - nice_view_header
features:
  - keys
  - display
  - underglow
siblings:
  - hillside46_left
  - hillside46_right
